services:
  # SQL Server Database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eyespire-backend-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass2762004@
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=2048
    ports:
      - "1433:1433"
    volumes:
      - backend_sqlserver_data:/var/opt/mssql
    networks:
      - backend-network
    restart: unless-stopped
    mem_limit: 3g
    cpus: 2
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Pass2762004@' -C -Q 'SELECT 1'"]
      interval: 45s
      timeout: 15s
      retries: 5
      start_period: 60s

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eyespire-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=database
      - DB_PORT=1433
      - DB_NAME=Eyespire_v0
      - DB_USERNAME=sa
      - DB_PASSWORD=Pass2762004@
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80,http://localhost
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - backend_uploads:/app/uploads

volumes:
  backend_sqlserver_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  backend-network:
    driver: bridge
